-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "growthScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "saturationLevel" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "trendScore" DOUBLE PRECISION DEFAULT 0;
